"""empty message

Revision ID: 758030d76ac2
Revises: 025ee6bff1c8
Create Date: 2021-10-21 15:56:46.506510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "758030d76ac2"
down_revision = "025ee6bff1c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("points", sa.Integer(), default=0, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "points")
    # ### end Alembic commands ###
