version: "3.8"
services:
  order_service:
    image: tanjd/order_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    volumes:
      - .:/order_service
    depends_on:
      - order_db
    links:
      - order_db:db
    environment:
      - dbURL=postgresql://postgres:postgres@order_db:5435/postgres

  order_db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5435"
    ports:
      - "5435:5435"
    command: -p 5435

volumes:
  db-data:
