"""empty message

Revision ID: 7d21331e6d0c
Revises: 529aecce9efb
Create Date: 2021-10-30 09:43:55.476351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d21331e6d0c'
down_revision = '529aecce9efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('product_name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'product_name')
    # ### end Alembic commands ###
